import {
  AdminStats,
  PatientUser,
  MedicationSchedule,
  MedicalProduct,
  HealthArticle,
  HealthProgram,
  ComplianceReport,
} from '../types/admin.types'

export const mockAdminStats: AdminStats = {
  totalPatients: 148,
  activeSchedules: 312,
  adherenceRate: 88.5,
  publishedArticles: 24,
  activePrograms: 6,
  lowStockProducts: 3,
}

export const initialPatients: PatientUser[] = [
  {
    id: 'PAT-001',
    name: 'Budi Santoso',
    age: 58,
    gender: 'Laki-laki',
    phone: '0812-3456-7890',
    email: 'budi.santoso@email.com',
    riskLevel: 'Tinggi',
    status: 'Aktif',
    assignedDoctor: 'dr. Siti Rahma, Sp.PD',
    activeSchedulesCount: 4,
    adherenceRate: 65,
    lastActive: 'Hari ini, 08:30',
    joinDate: '12 Jan 2025',
    medicalNotes: 'Pasien hipertensi derajat 2, butuh pengawasan pola konsumsi garam.',
  },
  {
    id: 'PAT-002',
    name: 'Siti Aminah',
    age: 62,
    gender: 'Perempuan',
    phone: '0813-9876-5432',
    email: 'siti.aminah@email.com',
    riskLevel: 'Sedang',
    status: 'Aktif',
    assignedDoctor: 'dr. Ahmad Dahlan, Sp.JP',
    activeSchedulesCount: 3,
    adherenceRate: 85,
    lastActive: 'Hari ini, 07:15',
    joinDate: '28 Feb 2025',
    medicalNotes: 'Diabetes Melitus Tipe 2 teratur minum metformin.',
  },
  {
    id: 'PAT-003',
    name: 'Hendra Gunawan',
    age: 45,
    gender: 'Laki-laki',
    phone: '0857-1122-3344',
    email: 'hendra.g@email.com',
    riskLevel: 'Rendah',
    status: 'Aktif',
    assignedDoctor: 'dr. Siti Rahma, Sp.PD',
    activeSchedulesCount: 2,
    adherenceRate: 96,
    lastActive: 'Kemarin, 20:00',
    joinDate: '15 Mar 2025',
    medicalNotes: 'Pemeriksaan rutin pasca rawat jalan.',
  },
  {
    id: 'PAT-004',
    name: 'Dewi Lestari',
    age: 51,
    gender: 'Perempuan',
    phone: '0819-5566-7788',
    email: 'dewi.lestari@email.com',
    riskLevel: 'Tinggi',
    status: 'Aktif',
    assignedDoctor: 'dr. Budi Setiawan, Sp.A',
    activeSchedulesCount: 5,
    adherenceRate: 74,
    lastActive: '2 hari lalu',
    joinDate: '04 Apr 2025',
    medicalNotes: 'Perlu pengingat khusus karena sering lupa minum obat malam.',
  },
  {
    id: 'PAT-005',
    name: 'Rudi Hartono',
    age: 67,
    gender: 'Laki-laki',
    phone: '0821-3344-5566',
    email: 'rudi.hartono@email.com',
    riskLevel: 'Sedang',
    status: 'Aktif',
    assignedDoctor: 'dr. Ahmad Dahlan, Sp.JP',
    activeSchedulesCount: 3,
    adherenceRate: 89,
    lastActive: 'Hari ini, 09:10',
    joinDate: '10 Mei 2025',
    medicalNotes: 'Penyakit jantung koroner stabil.',
  },
]

export const initialSchedules: MedicationSchedule[] = [
  {
    id: 'SCH-101',
    patientId: 'PAT-001',
    patientName: 'Budi Santoso',
    medicationName: 'Amlodipine 10mg',
    dosage: '1 Tablet',
    frequency: '1x Sehari',
    timeSlots: ['07:00'],
    startDate: '2025-01-15',
    endDate: '2025-08-15',
    status: 'Aktif',
    category: 'Obat Resep',
    instructions: 'Diminum pagi hari setelah makan.',
  },
  {
    id: 'SCH-102',
    patientId: 'PAT-001',
    patientName: 'Budi Santoso',
    medicationName: 'Metformin 500mg',
    dosage: '1 Tablet',
    frequency: '2x Sehari',
    timeSlots: ['08:00', '20:00'],
    startDate: '2025-01-15',
    endDate: '2025-08-15',
    status: 'Aktif',
    category: 'Obat Resep',
    instructions: 'Diminum bersamaan dengan makanan.',
  },
  {
    id: 'SCH-103',
    patientId: 'PAT-002',
    patientName: 'Siti Aminah',
    medicationName: 'Candesartan 8mg',
    dosage: '1 Tablet',
    frequency: '1x Sehari',
    timeSlots: ['06:30'],
    startDate: '2025-03-01',
    endDate: '2025-09-01',
    status: 'Aktif',
    category: 'Obat Resep',
    instructions: 'Diminum sebelum sarapan.',
  },
  {
    id: 'SCH-104',
    patientId: 'PAT-003',
    patientName: 'Hendra Gunawan',
    medicationName: 'Vitamin D3 2000 IU',
    dosage: '1 Kapsul',
    frequency: '1x Sehari',
    timeSlots: ['12:00'],
    startDate: '2025-03-20',
    endDate: '2025-09-20',
    status: 'Aktif',
    category: 'Suplemen',
    instructions: 'Diminum siang hari setelah makan siang.',
  },
  {
    id: 'SCH-105',
    patientId: 'PAT-004',
    patientName: 'Dewi Lestari',
    medicationName: 'Atorvastatin 20mg',
    dosage: '1 Tablet',
    frequency: '1x Sehari',
    timeSlots: ['21:00'],
    startDate: '2025-04-10',
    endDate: '2025-10-10',
    status: 'Aktif',
    category: 'Obat Resep',
    instructions: 'Diminum malam hari sebelum tidur.',
  },
]

export const initialProducts: MedicalProduct[] = [
  {
    id: 'PRD-001',
    name: 'Amlodipine Besylate 10mg',
    category: 'Obat Resep',
    sku: 'MED-AML-10',
    stock: 450,
    unit: 'Tablet',
    price: 15000,
    status: 'Tersedia',
    description: 'Obat antihipertensi golongan calcium channel blocker.',
  },
  {
    id: 'PRD-002',
    name: 'Metformin HCl 500mg',
    category: 'Obat Resep',
    sku: 'MED-MET-500',
    stock: 18,
    unit: 'Strip',
    price: 12000,
    status: 'Stok Menipis',
    description: 'Obat antidiabetes lini pertama untuk diabetes melitus tipe 2.',
  },
  {
    id: 'PRD-003',
    name: 'Vitamin D3 2000 IU Softgel',
    category: 'Suplemen',
    sku: 'SUP-VD3-2000',
    stock: 120,
    unit: 'Botol',
    price: 85000,
    status: 'Tersedia',
    description: 'Suplemen penunjang daya tahan tubuh dan kesehatan tulang.',
  },
  {
    id: 'PRD-004',
    name: 'Candesartan Cilexetil 8mg',
    category: 'Obat Resep',
    sku: 'MED-CND-08',
    stock: 5,
    unit: 'Box',
    price: 42000,
    status: 'Stok Menipis',
    description: 'Obat penurun tekanan darah tinggi golongan ARB.',
  },
  {
    id: 'PRD-005',
    name: 'Tensimeter Digital Omron',
    category: 'Alat Kesehatan',
    sku: 'ALT-TNS-OMR',
    stock: 0,
    unit: 'Unit',
    price: 650000,
    status: 'Habis',
    description: 'Alat pengukur tekanan darah otomatis presisi tinggi.',
  },
]

export const initialArticles: HealthArticle[] = [
  {
    id: 'ART-001',
    title: 'Panduan Praktis Mengontrol Hipertensi di Rumah',
    category: 'Hipertensi',
    author: 'dr. Siti Rahma, Sp.PD',
    publishDate: '2025-07-20',
    status: 'Terbit',
    views: 1420,
    summary: 'Langkah mudah memantau tekanan darah harian, mengatur pola makan kurangi garam, dan mengelola stres.',
    readTime: '5 min read',
  },
  {
    id: 'ART-002',
    title: 'Pola Makan Gizi Seimbang Untuk Penderita Diabetes',
    category: 'Diabetes',
    author: 'Nutrisionis Andi Wijaya, S.Gz',
    publishDate: '2025-07-15',
    status: 'Terbit',
    views: 980,
    summary: 'Mengenal Indeks Glikemik makanan dan menyusun piring makan ideal harian.',
    readTime: '6 min read',
  },
  {
    id: 'ART-003',
    title: 'Pentingnya Konsistensi Minum Obat Sesuai Jam',
    category: 'Gaya Hidup',
    author: 'Apoteker Maya Indah, S.Farm',
    publishDate: '2025-07-10',
    status: 'Terbit',
    views: 2150,
    summary: 'Mengapa efektivitas obat hipertensi & diabetes sangat tergantung ketepatan waktu konsumsi.',
    readTime: '4 min read',
  },
  {
    id: 'ART-004',
    title: 'Manfaat Jalan Kaki 30 Menit Bagi Kesehatan Jantung',
    category: 'Kardiovaskular',
    author: 'dr. Ahmad Dahlan, Sp.JP',
    publishDate: '2025-07-25',
    status: 'Draf',
    views: 0,
    summary: 'Olahraga aerobik ringan yang aman untuk lansia dan penderita gangguan sirkulasi darah.',
    readTime: '4 min read',
  },
]

export const initialPrograms: HealthProgram[] = [
  {
    id: 'PRG-001',
    name: 'Program Kontrol Hipertensi Terpadu',
    code: 'HT-CARE-2025',
    description: 'Program pendampingan 12 minggu untuk kontrol tekanan darah dan penyesuaian gaya hidup sehat.',
    durationWeeks: 12,
    enrolledPatientsCount: 42,
    status: 'Aktif',
    targetCategory: 'Hipertensi',
    createdBy: 'dr. Siti Rahma, Sp.PD',
  },
  {
    id: 'PRG-002',
    name: 'Manajemen Mandiri Diabetes Tipe 2',
    code: 'DM-CARE-2025',
    description: 'Monitoring kadar gula darah harian dan bimbingan nutrisi gizi terpadu.',
    durationWeeks: 16,
    enrolledPatientsCount: 38,
    status: 'Aktif',
    targetCategory: 'Diabetes Melitus',
    createdBy: 'dr. Ahmad Dahlan, Sp.JP',
  },
  {
    id: 'PRG-003',
    name: 'Rehabilitasi Jantung Pasca Rawat Jalan',
    code: 'CARDIO-REHAB',
    description: 'Pemantauan aktivitas fisik bertahap dan kepatuhan minum obat jantung.',
    durationWeeks: 8,
    enrolledPatientsCount: 19,
    status: 'Aktif',
    targetCategory: 'Kardiovaskular',
    createdBy: 'dr. Ahmad Dahlan, Sp.JP',
  },
]

export const mockComplianceReports: ComplianceReport[] = [
  { date: 'Senin', takenCount: 280, missedCount: 20, adherencePercentage: 93.3 },
  { date: 'Selasa', takenCount: 295, missedCount: 15, adherencePercentage: 95.1 },
  { date: 'Rabu', takenCount: 270, missedCount: 30, adherencePercentage: 90.0 },
  { date: 'Kamis', takenCount: 288, missedCount: 22, adherencePercentage: 92.9 },
  { date: 'Jumat', takenCount: 260, missedCount: 40, adherencePercentage: 86.6 },
  { date: 'Sabtu', takenCount: 250, missedCount: 45, adherencePercentage: 84.7 },
  { date: 'Minggu', takenCount: 265, missedCount: 35, adherencePercentage: 88.3 },
]
