export { default as AdminSidebar } from './components/AdminSidebar'
export { default as AdminHeader } from './components/AdminHeader'
export { default as AdminDashboardView } from './components/AdminDashboardView'
export { default as UserManagementView } from './components/UserManagementView'
export { default as ScheduleManagementView } from './components/ScheduleManagementView'
export { default as ProductManagementView } from './components/ProductManagementView'
export { default as ArticleManagementView } from './components/ArticleManagementView'
export { default as ProgramManagementView } from './components/ProgramManagementView'
export { default as ReportAnalyticsView } from './components/ReportAnalyticsView'

export * from './types/admin.types'
export * from './api/mockAdminData'
